# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BambuCli < Formula
  desc "CLI for controlling BambuLab printers directly over MQTT/FTPS/camera."
  homepage "https://github.com/tobiasbischoff/bambu-cli"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobiasbischoff/bambu-cli/releases/download/v0.1.4/bambu-cli_0.1.4_darwin_amd64.tar.gz"
      sha256 "fbe52b74d631dc01b9397c9fb9a5ebfde9d43d5a66425fec5b3e7f6f8685b870"

      def install
        bin.install "bambu-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobiasbischoff/bambu-cli/releases/download/v0.1.4/bambu-cli_0.1.4_darwin_arm64.tar.gz"
      sha256 "174385f554d9439c3c374603eb06d6460153a0822589a1a7c5be0c47c7122df4"

      def install
        bin.install "bambu-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiasbischoff/bambu-cli/releases/download/v0.1.4/bambu-cli_0.1.4_linux_amd64.tar.gz"
      sha256 "ff6903ebe475d7c1efb8294b85fef4792184a02699eb130dd4e846d7700380d5"
      def install
        bin.install "bambu-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiasbischoff/bambu-cli/releases/download/v0.1.4/bambu-cli_0.1.4_linux_arm64.tar.gz"
      sha256 "fddc99a1a777bc9517f7376593e90f75410dbf2d5d289846160b8d1723d3acfe"
      def install
        bin.install "bambu-cli"
      end
    end
  end

  test do
    system "#{bin}/bambu-cli", "--help"
  end
end
