# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FizzyCli < Formula
  desc "CLI for the Fizzy kanban board."
  homepage "https://github.com/tobiasbischoff/fizzy-cli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tobiasbischoff/fizzy-cli/releases/download/v0.1.1/fizzy-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "04d9d06036234f90de1dd88c2e923b19a48f5bb150e01713434c6c4cebc67280"

      def install
        bin.install "fizzy-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tobiasbischoff/fizzy-cli/releases/download/v0.1.1/fizzy-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "83448bc3b5e35738a5eac9c16fad469799bdc5ab8c6d80ea5f2a67d2c8320ea3"

      def install
        bin.install "fizzy-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiasbischoff/fizzy-cli/releases/download/v0.1.1/fizzy-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "e965df03847d7f09f38ddb56f11d93aecffa7b6ae35e62830ea50c572facee23"
      def install
        bin.install "fizzy-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tobiasbischoff/fizzy-cli/releases/download/v0.1.1/fizzy-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "12f89e961e22c68718d8077a49dc2c07e4c0978efe8ca29e2973c66c3dfddbb2"
      def install
        bin.install "fizzy-cli"
      end
    end
  end

  test do
    system "#{bin}/fizzy-cli", "--help"
  end
end
